#! /usr/bin/bash

if [ "$#" == 1 ]
then
sed "s/^constants[ ]\+.\+[^0-9]$/& 0 0 0 0 0 0 0 0 0/" "$1" > converted.mdl
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
$DIR/mdl converted.mdl
else
echo "incorrect number of arguments"
fi
